#!/bin/sh

rsync -rav --delete -e 'ssh -i ./.scaleway' \
	--exclude '.*' \
	--exclude node_modules \
	. 'root@dyndns.jannisr.de:~/dyndns-server/'

ssh -i ./.scaleway 'root@dyndns.jannisr.de' "\
cd ~/dyndns-server
npm i --production
export NODE_ENV=production
forever stop dyndns-server
forever start -a --uid dyndns-server index.js"
